service: notes

frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function # This plugin help us apply iamRoleStatement to each function so that we don't have to apply it at resource level as it woud be applied to each function then

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  createNote:
    handler: functions/createNote.handler
    events:
      - http:
          method: post
          path: notes
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt notesTable.Arn # GetAtt is intrinsic function

  updateNote:
    handler: functions/updateNote.handler
    events:
      - http:
          method: put
          path: notes/{id}
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt notesTable.Arn # GetAtt is intrinsic function

  deleteNote:
    handler: functions/deleteNote.handler
    events:
      - http:
          method: delete
          path: notes/{id}
  getAllNotes:
    handler: functions/getAllNotes.handler
    events:
      - http:
          method: get
          path: notes

resources:
  Resources:
    notesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: notesId
            AttributeType: S
        KeySchema:
          - AttributeName: notesId
            KeyType: HASH # notesId is a hash key
