service: notes

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  createNote:
    handler: functions/createNote.handler
    events:
      - http:
          method: post
          path: notes
  updateNote:
    handler: functions/updateNote.handler
    events:
      - http:
          method: put
          path: notes/{id}
  deleteNote:
    handler: functions/deleteNote.handler
    events:
      - http:
          method: delete
          path: notes/{id}
  getAllNotes:
    handler: functions/getAllNotes.handler
    events:
      - http:
          method: get
          path: notes
